version: '3.4'

services:
  microserviciosiudmicroget:
    image: microserviciosiudmicroget
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 6052:6052
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
